spring:
  application:
    name: consumer01
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#服务名称
PRO01:
  ribbon:
#    策略名称
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
